version: '3.8'

services:
  user_service_api:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
      args:
        FOLDER: ./user_service/api_rest
    container_name: user_service_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - notification_service_grpc
      
  user_service_grpc:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
      args:
        FOLDER: ./user_service/grpc
    container_name: user_service_grpc
    ports:
      - "9797:9797"
    depends_on:
      - redis
      
  message_service_api:
    build:
      context: .
      dockerfile: ./message_service/Dockerfile
      args:
        FOLDER: ./message_service/api_rest
    ports:
      - "8181:8181"
    depends_on:
      - redis
      
  message_service_grpc:
    build:
      context: .
      dockerfile: ./message_service/Dockerfile
      args:
        FOLDER: ./message_service/grpc
    container_name: message_service_grpc
    ports:
      - "9696:9696"
    depends_on:
      - redis
      - user_service_grpc
      - notification_service_grpc
  
  notification_service_api:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
      args:
        FOLDER: ./notification_service/api_rest
    container_name: notification_service_api
    ports:
      - "8282:8282"
    depends_on:
      - redis
      
  notification_service_grpc:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
      args:
        FOLDER: ./notification_service/grpc
    container_name: notification_service_grpc
    ports:
      - "9898:9898"
    depends_on:
      - redis
      - frontend_service_grpc
  
  frontend_service_grpc:
    build:
      context: .
      dockerfile: ./frontend_service/Dockerfile
      args:
        FOLDER: ./frontend_service/grpc
    container_name: frontend_service_grpc
    ports:
      - "3030:3030"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
