class NotificationService:
    def CreateNotification(self, request, context): ...

    def SubscribeUser(self, request, context): ...

    def UnsubscribeUser(self, request, context): ...

    def CheckUserSubscribed(self, request, context): ...


def serve(): ...


if __name__ == "__main__":
    serve()
